//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Assetobj_prefab
    {
        public const string BundleName = "assetobj_prefab";
        public const string ASSETOBJ = "assetobj";
    }
    public class Battlescene_unity
    {
        public const string BundleName = "battlescene_unity";
        public const string BATTLESCENE = "battlescene";
    }
    public class Cubeadel_prefab
    {
        public const string BundleName = "cubeadel_prefab";
        public const string CUBEADEL = "cubeadel";
    }
    public class Sceneres_unity
    {
        public const string BundleName = "sceneres_unity";
        public const string SCENERES = "sceneres";
    }
    public class Spritetest_png
    {
        public const string BundleName = "spritetest_png";
        public const string SPRITETEST = "spritetest";
    }
    public class Testimage_png
    {
        public const string BundleName = "testimage_png";
        public const string TESTIMAGE = "testimage";
    }
    public class Textureexample1_png
    {
        public const string BundleName = "textureexample1_png";
        public const string TEXTUREEXAMPLE1 = "textureexample1";
    }
    public class Uimultipanel_prefab
    {
        public const string BundleName = "uimultipanel_prefab";
        public const string UIMULTIPANEL = "uimultipanel";
    }
}
